### PR TITLE
Add operation works incorrectly if property contains / or ~

### PR DESCRIPTION
**Pull request by andreycha**
See details [in the issue](https://github.com/mcintyre321/JsonDiffPatch/issues/2).

### CODE REVIEW

**Comment by mcintyre321** [comment]
Thanks for the PR!

**Comment by andreycha** [comment]
@mcintyre321 no problem! Will the new version be available in Nuget?

**Comment by mcintyre321** [comment]
Should be there already, it auto deploys after a merge.

**Comment by andreycha** [comment]
@mcintyre321 nice, thanks a lot!

**Pull request merged**
